export const LOGIN = "LOGIN";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

export const LOAD_USER = "LOAD_USER";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT = "LOGOUT";

//// Profile Types

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";

export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const CREATE_OR_UPDATE_USER_PROFILE = "CREATE_OR_UPDATE_USER_PROFILE";
export const CREATE_OR_UPDATE_USER_PROFILE_SUCCESS = "CREATE_OR_UPDATE_USER_PROFILE_SUCCESS";
export const CREATE_OR_UPDATE_USER_PROFILE_ERROR = "CREATE_OR_UPDATE_USER_PROFILE_ERROR";

